#!/usr/bin/python

import mongolog

import datetime
import re
import sys

logformat = r"""Class: (?P<class>[^\n]*) Instance: (?P<instance>[^\n]*)
Time: (?P<time>[^\n]*) Host: (?P<hostname>[^\n]*)
From: (?P<zsig>.*) <(?P<sender>.*)>

(?P<body>.*)\n*"""

logformat_re = re.compile(logformat, re.MULTILINE | re.DOTALL)

header = r"""Class: (?P<class>[^\n]*) Instance: (?P<instance>[^\n]*)
Time: (?P<time>[^\n]*) Host: (?P<hostname>[^\n]*)
From: (?P<zsig>.*) <(?P<sender>.*)>"""

header_re = re.compile(header, re.MULTILINE | re.DOTALL)

def process(files):
    database = mongolog.db_connect(mongolog.read_config())
    messages = database.messages
    for filename in files:
        fd = open(filename, 'r')
        text = fd.read()
        matches = header_re.split(text)
        print len(matches), matches
        matches = []
        while True:
            match = logformat_re.match(text)
            if match:
                time = datetime.datetime.strptime(match.group("time"), "%a %b  %d %H:%M:%S %Y")
                matches.append((time, match))
                text = text[match.end():]
            else:
                break
        print text
        i = 0
        print len(matches)
        while i < len(matches):
            time, match = matches[i]
            fields = match.groupdict()
            fields['time'] = time
            j = i+1
            while j < len(matches):
                if matches[j][0] < matches[i][0]:
                    fields['body'] += matches[j][1].group('body')
                else:
                    break
            print i, j, time, fields
            i = j
        print "Done with %s" % (filename, )

if __name__ == "__main__":
    process(sys.argv[1:])
